### K Fold Cross Validation Exercise

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
import numpy as np

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

<h5>Logistic Regrssion</h5>

In [4]:
lr_score = cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target)
lr_score

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [5]:
average_lr_score = np.mean(lr_score)
average_lr_score

0.9733333333333334

<h5>Support Vector Machine</h5>

In [6]:
svm_score = cross_val_score(SVC(),iris.data,iris.target)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [7]:
average_svm_score = np.mean(svm_score)
average_svm_score

0.9666666666666666

<h5>Decision Tree</h5>

In [8]:
dt_score = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
dt_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [9]:
average_dt_score = np.mean(dt_score)
average_dt_score

0.9600000000000002

<h5>Random Forest</h5>

In [10]:
rf_score = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [11]:
average_rf_score = np.mean(rf_score)
average_rf_score

0.96

In [12]:
##parameter Tuning
rf_score = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [13]:
average_rf_score = np.mean(rf_score)
average_rf_score

0.96

##### Best Score from Logistic Regression : 0.9733333333333334